title: Arch Style Classifier Web
description: A web app to classify architectural styles
# theme: Architect  # Or any theme like jekyll-theme-cayman, etc.
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# title: Cat vs Dog Classifier