title: Arch Style Classifier Web
description: A web app to classify architectural styles
baseurl: "" # leave empty for root
url: "https://huggingface.co/spaces/adilsiraju/minimal" # deployed site URL

theme: minima

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation (only homepage)
header_pages:
  - index.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Custom variables
author: Adila